### ISSUE TITLE
dev-libs/libappindicator/libappindicator-12.10.1_p0_p0402_p20130920.ebuild tries to download wrong file

### ISSUE THREAD

**Issue by and3k** [shiznix/unity-gentoo#103]
It tries to download `libappindicator_12.10.1+13.10.220130920.orig.tar.gz`, but I think it sould try to download `libappindicator_12.10.1+13.10.20130920.orig.tar.gz`? (https://launchpad.net/ubuntu/+source/libappindicator/12.10.1+13.10.20130920-0ubuntu4.2)

**Comment by shiznix** [comment]
Should be fixed in commit 203ab90f5df592099bd33651f67886f0f84f876b - thanks for reporting!
