### ISSUE TITLE
gnome-extra/libgsf masked incorrectly?

### ISSUE THREAD

**Issue by and3k** [shiznix/unity-gentoo#106]
Hi,

commit 311c006cecd0b42d3b83c4e86e1a7e5cd7dd865c masked all instances of gnome-extra/libgsf (which I need). Was that on purpose?

Thanks!

**Comment by shiznix** [comment]
Definitely not on purpose.
Should be fixed in commit a6ba4eb8452cb1282e100c181016ef390fdca093 and thanks for reporting.

Not the tidiest way to mask gnome-3.14 but it's the best we've got so far without specifying every single gnome-3.14 package.

**Comment by and3k** [comment]
Looks good! Thanks
