### ISSUE TITLE
[Vivid] Couldn't build mesa::unity-gentoo

### ISSUE THREAD

**Issue by CyberTailor** [shiznix/unity-gentoo#108]
[An error and emerge --info](http://fpaste.org/202651/)

**Comment by shiznix** [comment]
Your paste has disappeared.
Can you use a different pastebin provider ?

Unless you want to develop the Vivid packages, then you probably want the Utopic profile.

**Comment by shiznix** [comment]
Closing now, feel free to re-open if you can provide info, thanks.
