### ISSUE TITLE
[humble ebuild request] indicator-privacy

### ISSUE THREAD

**Issue by and3k** [shiznix/unity-gentoo#109]
Hi!

This sound pretty useful/interesting: http://www.florian-diesch.de/software/indicator-privacy/

Maybe you wanna add it?

Thanks,
Bela

**Comment by shiznix** [comment]
Looks good, added in commit 62a0c9f848250365bc1615f07e73e6719b5e28be

**Comment by and3k** [comment]
Excellent. Seems to work properly. Thanks!

But shouldn’t the category be unity-indicators?

**Comment by shiznix** [comment]
Good to hear it works for you too :)

All those 3rd party packages not included by Ubuntu land in unity-extra/
