### ISSUE TITLE
No profile on arm devices.

### ISSUE THREAD

**Issue by MiningMarsh** [shiznix/unity-gentoo#111]
There is no arm profile, so this overlay cannot easily be used on arm devices.

**Comment by shiznix** [comment]
Hi MiningMarsh,

We currently don't have either the hardware, time or interest to test for arm architecture.
But you are most welcome to submit any pull requests to enable such support.

It is certainly something we wish to add in the coming months/years as soon as Unity8 matures enough to be useful on both desktop PC and Android phone.

It is for this same reason only amd64 and x86 keyword arch's are currently used in all the ebuilds.

**Comment by MiningMarsh** [comment]
I have a tegra k1 device I am using this overlay with, I would be interested in adding the arm profiles. I can only test this on an armv7a device though. If the install works, would you still be interested if I only add an arm profile for armv7a devices, and not the rest of the arm profiles?

**Comment by renegart** [comment]
Of cause! It makes no sense to enable profiles without able to test it. If you can get it run on the Tegra, it would be great. :)
