### ISSUE TITLE
[FUNTOO] Unity profiles not listed, eselect profile deprecated

### ISSUE THREAD

**Issue by XenHat** [shiznix/unity-gentoo#121]
I am unable to emerge unity on my funtoo machine;
1. The `eselect profile` command is deprecated and the output instructs the user to use `epro` instead.
2. `epro list` contains no unity-related profiles.

How am I supposed to emerge unity then?

Some additional info:
````
flailtop xenhat # epro list

=== arch: ===

    arm-32bit, pure64, (x86-32bit*), x86-64bit

=== subarch: ===

    amd64-k8+sse3_32, amd64-k8_32, athlon, athlon-4, athlon-mp
    athlon-tbird, athlon-xp, atom_32, btver1, core2_32, generic_32
    geode, i486, i686, k6, k6-2, k6-3, native_32, pentium, pentium-m*
    pentium-mmx, pentium2, pentium3, pentium4, pentiumpro, prescott
    xen-pentium4+sse3

=== build: ===

    (current*), experimental, stable

=== flavor: ===

    core, desktop*, hardened, minimal, server, workstation

=== mix-ins: ===

    X, audio, cinnamon, console-extras, dvd, gnome, gnome-3.16-fixups
    hardened, kde, lxde, lxqt, mate, media, media-pro, mediadevice-audio-consumer
    mediadevice-audio-pro, mediadevice-base, mediadevice-video-consumer
    mediadevice-video-pro, mediaformat-audio-common, mediaformat-audio-extra
    mediaformat-gfx-common, mediaformat-gfx-extra, mediaformat-video-common
    mediaformat-video-extra, no-emul-linux-x86, no-systemd, openvz-host
    print, python3-only, vmware-guest, xfce
````

**Comment by shiznix** [comment]
We'll need your help here XenHat.

Are you able to perhaps fork the overlay, get the existing profiles added to a Funtoo friendly profiles format and submit a pull request?

I for one have no idea what epro is expecting to see, or if it's even capable of reading custom profiles from overlays.
I expect it wouldn't be that much different yet from Gentoo's profiles, but even if I mash something together I currently have no Funtoo installation to test it on.

Thanks :)

**Comment by XenHat** [comment]
I had to install *Windows* on that same machine earlier this morning for technical reasons.
I will set up a new environment as soon as possible and see what I can do.

**Comment by XenHat** [comment]
I'm running into troubles setting this up in a virtual machine. I will report when I figure this out.

**Comment by XenHat** [comment]
I'm unable to read /dev/sda3 with the installed system, despite the sysrescue kernel can do it just fine. Re-installing Gentoo on my laptop (the machine I would consider putting bare metal linux on) would take several days again and I currently do not have the time for this. I'll keep in mind that funtoo isn't supported and I currently do not have the resources to add support for it.

**Comment by XenHat** [comment]
**Re-formulating my previous (deleted) comment:** I'm unable to read /dev/sda3 with the installed system, despite the sysrescue kernel being able to do it just fine. My laptop is currently not available for re-installation, so I'll need some time to figure what's wrong with the Hyper-V ATA module.

**Comment by XenHat** [comment]
I asked around and I was referred to http://www.funtoo.org/Creating_Profiles. I'll see what I can cook up.

**Comment by XenHat** [comment]
Apparently, unity requires systemd. That's a problem, since funtoo doesn't come with systemd by default. I'm *also* experiencing odd problems with `epro` where it won't list any profile created using their own tutorial.
I'm closing this issue for now, consider the resolution as "won't fix" since I'm not really going to bother with `epro`, which doesn't even have a properly updated tutorial.

**Comment by shiznix** [comment]
Thanks for trying anyway XenHat.
Perhaps there's a workaround to keep using 'eselect profile' on Funtoo?

**Comment by XenHat** [comment]
well, in theory one could recompile gentoo's eselect. but if unity needs systemd anyway, i'd rather just try it on gentoo.
