### ISSUE TITLE
<net-misc/networkmanager-1.0.6-r1 isn't available in gentoo any longer

### ISSUE THREAD

**Issue by susman** [shiznix/unity-gentoo#123]
https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=dab4f685feba4698fec68ef2f7ae9d66c36e7539

**Comment by shiznix** [comment]
Should be fixed in commit 6adfc92b2040a9eee74364ca1ee1787ac8ba6344

Thanks for reporting :)
