### ISSUE TITLE
mesa 11.0.7 removed

### ISSUE THREAD

**Issue by vafu** [shiznix/unity-gentoo#132]
cannot build mesa 11.0.7 'cause it has been removed from all the mirrors

**Comment by and3k** [comment]
It’s still there: https://github.com/shiznix/unity-gentoo/tree/master/media-libs/mesa ?

**Comment by shiznix** [comment]
@vafu Did you end up sorting why you can't access mesa-11.0.7?

Really need more info why you think it has been removed?

**Comment by shiznix** [comment]
Closing this now, feel free to re-open if you can provide more info - thanks :)

**Comment by vafu** [comment]
Sorry for being late.
I mean I cannot download the source code from any mirror 'cause it's absent.
e.g. https://download.nus.edu.sg/mirror/ubuntu/pool/main/m/mesa/
all of the mirrors now contain only 11.1.1 (which works fine for me now btw)

**Comment by shiznix** [comment]
Oops yes you're right!
Missed that one as it's a special package that requires we use the Xenial version so that Mir can build with it.

Should be fixed in commit a08b069a56469b884f90044f4244b4e339557944

Thanks for reporting :)
