### ISSUE TITLE
xkb layout switch

### ISSUE THREAD

**Issue by vafu** [shiznix/unity-gentoo#133]
Sadly, current layout switching managment of unity uses ibus or fcitx only, the settings-daemon strips all the "grp*" values of xkb.
here is a patch for unity-settings-daemon that reenables xkb again, but layout indicator is not affected on layout switch.
alternatively, there is an [xkb-keyboard-indicator](https://github.com/nightuser/xkb-keyboard-indicator) that looks exactly like default one and works just fine.

[unity-settings-daemon-dont_strip_grp.patch.zip](https://github.com/shiznix/unity-gentoo/files/113534/unity-settings-daemon-dont_strip_grp.patch.zip)
P.S. why doesn't github support direct plain-text attachment? oO

**Comment by shiznix** [comment]
What's upstream's reasoning for doing this?

I keep re-reading the comment for it in plugins/keyboard/gsd-keyboard-manager.c but still none the wiser.
I might need a translator for this:
        /* We might set up different layouts in different groups - see
         * replace_layout_and_variant(). But we don't want the X
         * server group switching feature to actually switch
         * them. Regularly, if we have at least two input sources,
         * gnome-shell will tell us to switch input source at that
         * point so we fix that automatically. But when there's only
         * one source, gnome-shell short circuits as an optimization
         * and doesn't call us so we can't set the group switching XKB
         * option in the first place otherwise the X server's switch
         * will take effect and we get a broken configuration. */

Any ideas?

**Comment by vafu** [comment]
>> What's upstream's reasoning for doing this?
Do you mean "reasoning" for applying the patch or why did they do it?

why did they do it — I can't really understand. 

"But we don't want the X server group switching feature to actually switch them" 
Here is the question with no answer.

**Comment by shiznix** [comment]
This bug report sheds some light -> https://bugs.launchpad.net/ubuntu/+source/unity-settings-daemon/+bug/1315867
