### ISSUE TITLE
dev-libs/glib-2.46.2_p1_p01: gdbusproxy-memleak_fix.diff missing

### ISSUE THREAD

**Issue by c4pp4** [shiznix/unity-gentoo#136]
* Package:    dev-libs/glib-2.46.2_p1_p01
 * Repository: unity-gentoo
 * Maintainer: unity-gentoo overlay
 * Upstream:   https://github.com/shiznix/unity-gentoo/issues
 * USE:        abi_x86_64 amd64 dbus elibc_glibc kernel_linux mime python_targets_python2_7 userland_GNU utils xattr
 * FEATURES:   preserve-libs sandbox userpriv usersandbox
 * Determining the location of the kernel source code
 * Found kernel source directory:
 *     /usr/src/linux
 * Found kernel object directory:
 *     /lib/modules/4.4.6-gentoo/build
 * Found sources for kernel version:
 *     4.4.6-gentoo
 * Checking for suitable kernel configuration options...                                                                                                                                                     [ ok ]
>>> Unpacking source...
>>> Unpacking glib2.0_2.46.2.orig.tar.xz to /var/tmp/portage/dev-libs/glib-2.46.2_p1_p01/work
>>> Unpacking pkg-config-0.28.tar.gz to /var/tmp/portage/dev-libs/glib-2.46.2_p1_p01/work
>>> Source unpacked in /var/tmp/portage/dev-libs/glib-2.46.2_p1_p01/work
>>> Preparing source in /var/tmp/portage/dev-libs/glib-2.46.2_p1_p01/work/glib-2.46.2 ...
 * Applying glib-2.40.0-external-gdbus-codegen.patch ...                                                                                                                                                     [ ok ]

 * Cannot find $EPATCH_SOURCE!  Value for $EPATCH_SOURCE is:
 * 
 *   **/var/lib/layman/unity-gentoo/dev-libs/glib/files/gdbusproxy-memleak_fix.diff**
 *   ( gdbusproxy-memleak_fix.diff )

 * ERROR: dev-libs/glib-2.46.2_p1_p01::unity-gentoo failed (prepare phase):
 *   Cannot find $EPATCH_SOURCE!
 * 
 * Call stack:
 *     ebuild.sh, line  133:  Called src_prepare
 *   environment, line 6156:  Called epatch '-p1' '/var/lib/layman/unity-gentoo/dev-libs/glib/files/gdbusproxy-memleak_fix.diff'
 *   environment, line 2091:  Called die
 * The specific snippet of code:
 *                   die "Cannot find \$EPATCH_SOURCE!";
 * 
 * If you need support, post the output of `emerge --info '=dev-libs/glib-2.46.2_p1_p01::unity-gentoo'`,
 * the complete build log and the output of `emerge -pqv '=dev-libs/glib-2.46.2_p1_p01::unity-gentoo'`.
 * The complete build log is located at '/var/tmp/portage/dev-libs/glib-2.46.2_p1_p01/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-libs/glib-2.46.2_p1_p01/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-libs/glib-2.46.2_p1_p01/work/glib-2.46.2'
 * S: '/var/tmp/portage/dev-libs/glib-2.46.2_p1_p01/work/glib-2.46.2'

**Comment by shiznix** [comment]
Should be fixed in commit 35318d5821e747535f9635d39c21f227c20a7899

Thanks for reporting :)
