### ISSUE TITLE
dev-qt/qtgui-5.5.1_p16_p0701: missing dev-qt/qtnetwork

### ISSUE THREAD

**Issue by c4pp4** [shiznix/unity-gentoo#141]
Overlay version is without flag "tuio" so it needs dev-qt/qtnetwork installed. Take a look at here https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-qt/qtgui/qtgui-5.5.1-r1.ebuild

...
Project ERROR: Unknown module(s) in QT: network
Makefile:146: recipe for target 'sub-tuiotouch-make_first' failed
make: *** [sub-tuiotouch-make_first] Error 3
...

**Comment by shiznix** [comment]
Should be fixed in commit 47457ae4cb168154d6ab0bfb2511ed1d106f6faf

Thanks for reporting :)
