### ISSUE TITLE
qt minimal version raised to 5.6.1

### ISSUE THREAD

**Issue by and3k** [shiznix/unity-gentoo#143]
Hi!

The minimum version of qt was raised to >=5.6.1: https://gitweb.gentoo.org/repo/gentoo.git/commit/eclass?id=e8ab1548802b6e545e76d24b610cbb5245f3276a

Since all these qt packages are masked by gentoo-unity, this breaks **all** KDE and some other package deps.

Not sure how to work around this? :)

Thanks,
Bela

**Comment by shiznix** [comment]
Thanks Bela seeing now if we can start to use qt-5.6 for Unity packages.

For ref. here we started maintaining our own set of QT5 ebuilds as they hadn't made it into portage yet + Ubuntu were issuing patches to be able to support QML and Mir EGL for their Unity8 desktop.

Would be ideal if these patches have been accepted upstream and save so much time to not maintain QT5 in overlay.

Will update this issue with further progress...

**Comment by shiznix** [comment]
Some good progress made, qt-5.6 installed with no problem and apart from a small patch for ubuntu-ui-toolkit all the overlay packages that depend on QT5 seem to build and run just fine.

Just doing a final cleanup now to commit shortly...

**Comment by shiznix** [comment]
Seems to work ok, closing as fixed now...

**Comment by and3k** [comment]
Thanks. Worked perfectly!
