### ISSUE TITLE
packages with $(vala_depend) are masked

### ISSUE THREAD

**Issue by c4pp4** [shiznix/unity-gentoo#144]
All vala dependent packages are masked by: invalid: DEPEND: expected: dependency string, got: ')'.

Please change VALA_MAX_API_VERSION (ubuntu-versionator.eclass) because they've dropped vala 0.22:
https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=1041ddca80dfcb73de03299fe736c078e32aec24

**Comment by shiznix** [comment]
Should be fixed in commit f65a39570b84d87d97fb38becff81e52dcf029fc

Thanks for reporting :)
