### ISSUE TITLE
[~amd64] gtk+-3.20 needed by webkit-gtk-2.4.11

### ISSUE THREAD

**Issue by and3k** [shiznix/unity-gentoo#146]
Hi,

FYI: the newest ebuild of webkit-gtk/webkit-gtk-2.4.11-r1 needs gtk3-3.20 "to ensure we get fixed theming: https://bugzilla.gnome.org/show_bug.cgi?id=757503" (https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=f392c39b16b2e23b9ab7f7749f4f479a0f8f5722). However, gtk3-3.20 is masked by this repo.

Masking webkit-gtk/webkit-gtk-2.4.11-r1 is a workaround for now.

Best,
Bela

**Comment by shiznix** [comment]
Fixed in commit c4bf3ed678ed72699a11e4f2e092080a5df75161
Thanks again Bela :)
