### ISSUE TITLE
[~amd64] nux doesn’t build with glew-2.0.0

### ISSUE THREAD

**Issue by and3k** [shiznix/unity-gentoo#147]
Hi,

here’s another FYI/bug from ~amd64:

when glew-2.0.0 is installed I get this error when building nux:

```
configure: error: Package requirements (glib-2.0 >= 2.25.14
                  gdk-pixbuf-2.0
                  cairo >= 1.9.14
                  libpng >= 1.2.44
                  gl glu glew glewmx xext x11
                  xxf86vm
                  sigc++-2.0
                              xinerama
                  ) were not met:

No package 'glewmx' found
```

Thanks,
Bela

**Comment by shiznix** [comment]
Unable to do much more than include '<media-libs/glew-2.0.0' in unity-base/nux ebuild until nux supports >=glew-2.0.0

Fixed in commit fe75cebc03b11f472ac08231e3d5366b5e76ef58
