### ISSUE TITLE
[~amd64] sys-devel/binutils-2.26 breaks firefox

### ISSUE THREAD

**Issue by and3k** [shiznix/unity-gentoo#148]
Hi,

and another one:

updating sys-devel/binutils to testing version 2.26.1 triggers the [firefox ebuild to patch xpcom-components-binutils-26.patch](https://github.com/shiznix/unity-gentoo/blob/master/www-client/firefox/firefox-48.0_p0_p00160401.ebuild#L134), which is missing from this overlay.

Copying the patch from the main repo seems to work.

Thanks,
Bela

**Comment by shiznix** [comment]
Fixed in commit 79d71b9553c9dba9b60af2a6bb6821eaf185b80b
Thanks for reporting :)
