### ISSUE TITLE
net-libs/libsoup-gnome is masked in main repo, breaking some package deps

### ISSUE THREAD

**Issue by and3k** [shiznix/unity-gentoo#149]
Hi!

net-libs/libsoup-gnome is hard masked in the main overlay ("Obsolete for years in favour of plain libsoup usage. Removal in a month."). This breaks unity-scopes/unity-scope-home-6.8.2_p0_p01_p2016021201, unity-lenses/unity-lens-photos-1.0_p0_p01, etc

Thanks,
Bela

**Comment by eyoung100** [comment]
@shiznix Is it possible to remove net-libs/libsoup-gnome from the RDEPENDS section of the affected ebuilds?  What happens when doing so?

**Comment by shiznix** [comment]
Fixed in commit 07a3a6a29d8130fba71ce8ae365fef6497f815bd
Thanks for reporting :)

@eyoung100 Able to remove from unity-lens-music but other lenses and banshee still require it.
