### ISSUE TITLE
Languages

### ISSUE THREAD

**Issue by c4pp4** [shiznix/unity-gentoo#155]
Some corrections related to languages.

**unity-base/unity-language-pack**
_Activity-log-manager and indicator-datetime po-files are in "language-pack-" folder instead of "language-pack-gnome-". Furthermore it should be save to add ubuntu-help po-file, because ubuntu-docs doesn't install it._
[unity-language-pack.diff.txt](https://github.com/shiznix/unity-gentoo/files/465406/unity-language-pack.diff.txt)

**gnome-extra/activity-log-manager**
_It's looking at "//" folder instead of "/usr/share/locale". (I've also removed some useless code snippets.)_
[activity-log-manager.diff.txt](https://github.com/shiznix/unity-gentoo/files/465407/activity-log-manager.diff.txt)

**unity-indicators/indicator-datetime**
_It's looking at "/locale" folder instead of "/usr/share/locale"._
[indicator-datetime.diff.txt](https://github.com/shiznix/unity-gentoo/files/465409/indicator-datetime.diff.txt)

**unity-indicators/indicator-sound**
_It's looking at "/locale" folder instead of "/usr/share/locale"._
[indicator-sound.diff.txt](https://github.com/shiznix/unity-gentoo/files/465410/indicator-sound.diff.txt)

**unity-indicators/indicator-session**
_Renaming "menu, help_label" to "menu, _("Unity Help")" is not ideal, because it's not translated then._
[indicator-session.diff.txt](https://github.com/shiznix/unity-gentoo/files/465412/indicator-session.diff.txt)
[unity.patch.txt](https://github.com/shiznix/unity-gentoo/files/465413/unity.patch.txt)

**Comment by c4pp4** [comment]
Another issue: **Security & Privacy** launcher in **Unity Control Center** will never be translated, because its po-file is separated.

There is a one solution - to use this patch from Ubuntu's glib2 package:
[01_gettext-desktopfiles.patch.txt](https://github.com/shiznix/unity-gentoo/files/465423/01_gettext-desktopfiles.patch.txt)
Then you have to change activity-log-manager.ebuild with something like this:
`find ${S}/data -type f -name "*.desktop.in" -exec sh -c 'echo X-GNOME-Gettext-Domain=unity-control-center >> "$1"' -- {} \;`

I think all apps using unity-language-pack should have changed appropriate desktop-file.

**Comment by c4pp4** [comment]
I've gone through unity-gentoo repo and the following packages have an appropriate language file in unity-language-pack so we can remove them because unity-language-pack will always be more complete.

**language-pack-**
media-sound/pulseaudio
sys-apps/ureadahead
www-client/webbrowser-app
x11-misc/lightdm

**language-pack-gnome-**
app-accessibility/onboard
app-backup/deja-dup
gnome-base/nautilus
gnome-extra/activity-log-manager
gnome-extra/nm-applet
gnome-extra/polkit-gnome (polkit-gnome-1.po)
media-gfx/shotwell
media-sound/rhythmbox
net-libs/account-plugins
net-libs/gnome-online-accounts
net-libs/libsoup-gnome (libsoup.po)
sys-apps/accountsservice (accounts-service.po)
unity-base/hud
x11-libs/gtk+ (gtk20.po, gtk20-properties.po, gtk30.po, gtk30-properties.po)

**In case of patching glib2** - the following packages install desktop launchers so we can add into them "X-GNOME-Gettext-Domain":
app-accessibility/onboard
app-backup/deja-dup
gnome-base/nautilus
gnome-extra/activity-log-manager
gnome-extra/nm-applet
media-gfx/shotwell
media-sound/rhythmbox
unity-base/hud
www-client/webbrowser-app

**Comment by shiznix** [comment]
All looks good, will implement something over the next couple of days - thanks :)
