### ISSUE TITLE
x11-libs/content-hub-0.2_p20160914_p0_p01 fails to compile 

### ISSUE THREAD

**Issue by jetboo** [shiznix/unity-gentoo#168]
Hello there,

I can't compile x11-libs/content-hub-0.2_p20160914_p0_p01 on my system. Here is the log :

http://pastebin.com/hMWV1nTN

Any idea about what's wrong ? 

Cheers

**Comment by jetboo** [comment]
Fixed by emerging oxide-at-1.20.4_p_p0_p00161001

**Comment by shiznix** [comment]
Excellent, thanks for finding the solution.
