### ISSUE TITLE
Install Anbox without switching to Ubuntu profile?

### ISSUE THREAD

**Issue by Gooberpatrol66** [shiznix/unity-gentoo#175]
Would it be possible to make it possible to install Anbox without having to install a trillion unity packages?

**Comment by shiznix** [comment]
Sure, doesn't it do that already?

**Comment by Gooberpatrol66** [comment]
>Copy the required ebuilds for Anbox into your own overlay and use those by removing inheriting ubuntu-versionator.eclass.
Will the ebuilds still work if I do that?

**Comment by shiznix** [comment]
Yes they should still work.
