### ISSUE TITLE
[question] Can be anbox installed without depending on Unity?

### ISSUE THREAD

**Issue by archenroot** [shiznix/unity-gentoo#181]
Hi, 

thanks for ebuild for anbox, I tried to do hardcopy into my overlay, but later realized that the dbus-cpp package requires ubuntu-versionator eclass which bounds it to unity-gentoo profile, Is it supported to install dbus-cpp without Unity?

**Comment by archenroot** [comment]
Ok, I have progressed little bit by hard-copy your artifacts, I removed unity eclass stuff, but having real trouble with dbus-cpp project which is in state I cannot compile, so I am now debugging the CMake system on my laptop, will see how it goes...

**Comment by fpemud** [comment]
Install dev-cpp/gmock can solve your problem.
dev-cpp/gmock is missing in the dependency list of dev-libs/dbus-cpp.

**Comment by Gooberpatrol66** [comment]
I did. You have to copy ubuntu-versionator.eclass and the ebuilds for anbox, dbus-cpp, gmock, gtest, process-cpp, and properties-cpp to a local overlay, then comment out the pkg_setup, src_prepare and pkt_postinst functions in the eclass and remove references to them in the ebuilds.

**Comment by shiznix** [comment]
Should be fixed in commit 09a07420936a5a334d1e65e267ea413905c23005
