### ISSUE TITLE
Installation problems in Sabayon

### ISSUE THREAD

**Issue by Ptero-4** [shiznix/unity-gentoo#188]
The unity-gentoo overlay is unusable on Sabayon because it demands a specific profile and the portage profile functionality has been disabled on Sabayon because of the integration between the portage package system Sabayon adopted from gentoo and the entropy binary package manager Sabayon uses as primary package manager.

**Comment by c4pp4** [comment]
`eselect profile list` and `eselect profile set <number>` as root doesn't work?

**Comment by shiznix** [comment]
Similar to issue #121 it seems.
That is, Gentoo derivatives such as Funtoo and Sabayon that change the core functionality of how profiles work.
If it works on those distros well that's a bonus, but it's certainly not supported.

**Comment by shiznix** [comment]
Closing this one now...
