### ISSUE TITLE
ido is out of date.

### ISSUE THREAD

**Issue by JinxAdnix** [shiznix/unity-gentoo#191]
The version of ido you are pulling in is an old one that seems to no longer be available.

**Comment by JinxAdnix** [comment]
It seems the problem is actually with the mirrors. For now you can manually download the files here and copy then to your distfiles.

https://launchpad.net/ubuntu/+source/ido/13.10.0+17.04.20161028-0ubuntu1

**Comment by shiznix** [comment]
Fixed in commit 7be6d5a9cb6143f0c5c85759a1f52bd436c09394 thanks for reporting :)
