### ISSUE TITLE
>=sys-apps/portage-2.3.26 breaks all ehooks that apply patches

### ISSUE THREAD

**Issue by shiznix** [shiznix/unity-gentoo#193]
`>>> Emerging (1 of 1) www-client/firefox-59.0.2::gentoo
 * firefox-59.0.2-en-GB.xpi BLAKE2B SHA512 size ;-) ...                                                                                                                  [ ok ]
 * firefox-59.0.2.source.tar.bz2 BLAKE2B SHA512 size ;-) ...                                                                                                             [ ok ]
 * firefox-59.0-patches-01.tar.xz BLAKE2B SHA512 size ;-) ...                                                                                                            [ ok ]
>>> Loading unity-gentoo ebuild hook from /usr/local/portage/unity-gentoo/profiles/releases/artful/ehooks/www-client/firefox ...
 * Processing 01-pre_pkg_setup.ehook ...
>>> Done.
 * 
 * You are enabling official branding. You may not redistribute this build
 * to any users on your network or the internet. Doing so puts yourself into
 * a legal problem with Mozilla Foundation
 * You can disable it by emerging firefox _with_ the bindist USE-flag
>>> Unpacking source...
>>> Unpacking firefox-59.0.2-en-GB.xpi to /ubuntu/var/tmp/portage/www-client/firefox-59.0.2/work
unpack firefox-59.0.2-en-GB.xpi: file format not recognized. Ignoring.
>>> Unpacking firefox-59.0.2.source.tar.bz2 to /ubuntu/var/tmp/portage/www-client/firefox-59.0.2/work
>>> Unpacking firefox-59.0-patches-01.tar.xz to /ubuntu/var/tmp/portage/www-client/firefox-59.0.2/work
 * Sorry, but firefox-59.0.2 does not support the en_AU locale in LINGUAS
 * Unpacking firefox-59.0.2-en-GB.xpi to /ubuntu/var/tmp/portage/www-client/firefox-59.0.2/work
 * Selected language packs (first will be default): en-GB
>>> Source unpacked in /ubuntu/var/tmp/portage/www-client/firefox-59.0.2/work
>>> Loading unity-gentoo ebuild hook from /usr/local/portage/unity-gentoo/profiles/releases/artful/ehooks/www-client/firefox ...
 * Processing 02-pre_src_prepare.ehook ...
 * Applying patches from /usr/local/portage/unity-gentoo/profiles/releases/artful/ehooks/www-client/firefox/files ...
 *   unity-menubar.patch ...                                                                                                                                             [ ok ]
 * ERROR: www-client/firefox-59.0.2::gentoo failed (prepare phase):
 *    * Applying patches from /usr/local/portage/unity-gentoo/profiles/releases/artful/ehooks/www-client/firefox/files ...
 *  *   unity-menubar.patch ...                                                                                                                                             [ ok ] 
 * 
 * Call stack:
 *        ebuild.sh, line 124:  Called pre_src_prepare
 *   profile.bashrc, line 194:  Called apply_ehook
 *   profile.bashrc, line 1106:  Called die
 * The specific snippet of code:
 * 
 * If you need support, post the output of `emerge --info '=www-client/firefox-59.0.2::gentoo'`,
 * the complete build log and the output of `emerge -pqv '=www-client/firefox-59.0.2::gentoo'`.
 * The complete build log is located at '/ubuntu/var/tmp/portage/www-client/firefox-59.0.2/temp/build.log'.
 * The ebuild environment file is located at '/ubuntu/var/tmp/portage/www-client/firefox-59.0.2/temp/environment'.
 * Working directory: '/ubuntu/var/tmp/portage/www-client/firefox-59.0.2/work/mozilla-release-239e434d6d2b8e1e2b697c3416d1e96d48fe98e5'
 * S: '/ubuntu/var/tmp/portage/www-client/firefox-59.0.2/work/mozilla-release-239e434d6d2b8e1e2b697c3416d1e96d48fe98e5'`

**Comment by shiznix** [comment]
Yup works well now with all portage versions above and below 2.3.26.
Have reverted removal in commit f019415b7c72f9a35d7042e0fa5e448bdf0eaf28

Thanks :)

**Comment by c4pp4** [comment]
This commit https://github.com/gentoo/portage/commit/2b62104633008cc30df24808029430516a6d9a7b#diff-f5f23332cd6468b68e6e2a09f67e7737 was causing the problem. They are sending ebegin and eend output to stderr. I think we can't handle errors of ebuild_hook now.

**Comment by c4pp4** [comment]
Maybe I find a solution. Temporarily redirect information messages (ebegin, einfo...) to fd 3 instead of stderr. I'm testing it now.
`source <(declare -f `**`ebegin`**` | sed -e "s/\(1>&\)2/\13/")`
`source <(declare -f `**`einfo`**` | sed -e "s/\(1>&\)2/\13/g")`
`source <(declare -f `**`einfon`**` | sed -e "s/\(1>&\)2/\13/g")`
`source <(declare -f `**`__eend`**` | sed -e "s/\(1>&\)2/\13/g")`

**Comment by c4pp4** [comment]
Should be resolved - 5770942
