### ISSUE TITLE
'x11-libs/dee-qt-3.3_p20140317_p0_p02' installs 'libdee-qt5.pc' to /usr/lib/pkgconfig and not /usr/lib64/pkgconfig

### ISSUE THREAD

**Issue by renegart** [shiznix/unity-gentoo#194]
The package 'x11-libs/dee-qt-3.3_p20140317_p0_p02' installs its .pc file into wrong lib directory on 64bit system.
Since it's not an issue on a 17.0 profile based systems, it breaks compilation of 'unity-base/hud' on 17.1 profile based systems

**Comment by c4pp4** [comment]
Should be fixed now - c914774

**Comment by renegart** [comment]
works. thx.
