### ISSUE TITLE
Launcher setting 'color by background image' causes black icons

### ISSUE THREAD

**Issue by renegart** [shiznix/unity-gentoo#196]
Since upgrade to artful profile all icons in launcher and hud are more or less black if you use color by background image setting in Unity Tweak Tool.

see attached files

![launcher_black_background](https://user-images.githubusercontent.com/3251787/39797166-edd9dbd8-535a-11e8-80ac-57acd11e7fa6.png)
![launcher_black_icons](https://user-images.githubusercontent.com/3251787/39797225-4b01fc5a-535b-11e8-8c9d-3548ece54e1e.png)
![launcher_black_icons_hud](https://user-images.githubusercontent.com/3251787/39797168-ee0e2c4e-535a-11e8-9449-7e361c1bc44b.png)

**Comment by c4pp4** [comment]
I'm not using unity tweak tool, but I guess you can try to reset that setting: `dconf reset -f /org/compiz/profiles/unity/plugins/unityshell/` or reset the whole compiz: `dconf reset -f /org/compiz/`.

**Comment by c4pp4** [comment]
I've tried it within Virtualbox. I can reproduce the same problem when I switch from 'custom color' to 'based on wallpaper' on Ubuntu 17.10. But after restart it looks normal again. Anyway I think it's unity-tweak-tool bug.

**Comment by shiznix** [comment]
Can reproduce here also.

Reading notes/launcher_color.txt in unity-tweak-tool's source tarball, it seems it's a limitation on how Unity implements it's Launcher....
"Issue: The launcher background colour is currently superimposed on the chamelonic launcher. The result is an awkward unpredictable mixture. This is a result of implementation in unity. Absolutely nothing can be done about it, unless the unity devs change their mind."

**Comment by shiznix** [comment]
Closing as odd colour behaviour is expected by upstream.
