### ISSUE TITLE
remove of basic set of 'wayland' breaks desktop, if  'x11-libs/gtk+', 'app-i18n/ibus' and 'gnome-base/gnome-desktop' are rebuild in one step

### ISSUE THREAD

**Issue by renegart** [shiznix/unity-gentoo#197]
'app-i18n/ibus' and 'gnome-base/gnome-desktop' have internal references to wayland and if there are not rebuild when 'wayland' as use flag is removed, it breaks the desktop

**Comment by c4pp4** [comment]
'app-i18n/ibus' and 'gnome-base/gnome-desktop' need to be build after 'x11-libs/gtk+:3', because 'x11-libs/gtk+:3' defines GDK_WINDOWING_WAYLAND identifier used by 'app-i18n/ibus' and 'gnome-base/gnome-desktop', but I think it should be solved by preserved-rebuild. It doesn't show that message about existing preserved libs after emerge world?

**Comment by renegart** [comment]
Nope. And I don't know, if it's possible to trigger the preserved rebuild via ebuild

**Comment by c4pp4** [comment]
https://bugs.gentoo.org/624960

**Comment by c4pp4** [comment]
I think app-misc/foo[**bar=**] should suffice. We can fix 'gnome-base/gnome-desktop', but we need to maintain 'app-i18n/ibus' package to fix it too.
e.g. 'gnome-base/gnome-desktop':
```
@@ -16,7 +16,7 @@
 
 LICENSE="GPL-2+ FDL-1.1+ LGPL-2+"
 SLOT="3/12" # subslot = libgnome-desktop-3 soname version
-IUSE="debug +introspection udev"
+IUSE="debug +introspection udev wayland"
 KEYWORDS="~amd64 ~x86"
 RESTRICT="mirror"
 
@@ -25,7 +25,7 @@
 	app-text/iso-codes
 	>=dev-libs/glib-2.44.0:2[dbus]
 	>=x11-libs/gdk-pixbuf-2.33.0:2[introspection?]
-	>=x11-libs/gtk+-3.3.6:3[X,introspection?]
+	>=x11-libs/gtk+-3.3.6:3[X,introspection?,wayland=]
 	x11-libs/cairo:=[X]
 	x11-libs/libX11
 	x11-misc/xkeyboard-config
```

**Comment by c4pp4** [comment]
If we include **app-i18n/ibus[wayland=]** into RDEPEND or PDEPEND in 'gnome-base/gnome-desktop' ebuild, it should suffice to be 'app-i18n/ibus' merged after 'x11-libs/gtk+:3' when wayland flag is changed. It could looks like this:
```
@@ -16,7 +16,7 @@
 
 LICENSE="GPL-2+ FDL-1.1+ LGPL-2+"
 SLOT="3/12" # subslot = libgnome-desktop-3 soname version
-IUSE="debug +introspection udev"
+IUSE="debug +introspection udev wayland"
 KEYWORDS="~amd64 ~x86"
 RESTRICT="mirror"
 
@@ -25,7 +25,7 @@
 	app-text/iso-codes
 	>=dev-libs/glib-2.44.0:2[dbus]
 	>=x11-libs/gdk-pixbuf-2.33.0:2[introspection?]
-	>=x11-libs/gtk+-3.3.6:3[X,introspection?]
+	>=x11-libs/gtk+-3.3.6:3[X,introspection?,wayland=]
 	x11-libs/cairo:=[X]
 	x11-libs/libX11
 	x11-misc/xkeyboard-config
@@ -37,6 +37,7 @@
 "
 RDEPEND="${COMMON_DEPEND}
 	!<gnome-base/gnome-desktop-2.32.1-r1:2[doc]
+	app-i18n/ibus[wayland=]
 "
 DEPEND="${COMMON_DEPEND}
 	app-text/docbook-xml-dtd:4.1.2

```
What do you think about it. And if it's a good idea, use RDEPEND or PDEPEND?

**Comment by shiznix** [comment]
All good, no need to start maintaining app-i18n/ibus and duplicate Gentoo main tree work on https://bugs.gentoo.org/624960

Have made a note and request on that bug that app-i18n/ibus ebuilds need the same 'wayland' USE attention, closing now as that bug is IN_PROGRESS.
