### ISSUE TITLE
'dev-libs/libdbusmenu-qt-0.9.3_p20160218_p1_p01-r1' doesn't compile for 32bit

### ISSUE THREAD

**Issue by renegart** [shiznix/unity-gentoo#198]
see: https://paste.pound-python.org/show/WrgsHDYk7Zv7sJZnvXnS/

seems the 32bit build tries to link against 64bit libraries

**Comment by c4pp4** [comment]
Have you tried version from main tree?

**Comment by renegart** [comment]
tried 'libdbusmenu-qt-0.9.3_pre20160218-r2.ebuild' from gentoo tree. It worked

**Comment by c4pp4** [comment]
I think we don't need to maintain own (duplicated) version.

**Comment by shiznix** [comment]
We needed the QT5 version before it made it into the main tree, then made it multilib so that KDE5 could use it (at least going by git logs)?

Feel free to remove.

**Comment by renegart** [comment]
I've removed the package
