### ISSUE TITLE
failed to download gmock*.debian.tar.gz

### ISSUE THREAD

**Issue by renegart** [shiznix/unity-gentoo#199]
The debian.tar.gz file is not available anymore on ubuntu mirrors
I've found a copy at https://mirror.raspbian.solit.systems/raspbian/pool/main/g/google-mock/ to continue work.
We should either change the mirror for that package or try to remove the dependency of gmock

**Comment by shiznix** [comment]
Fixed in commit ebebaa594df50d1225266cfef095eba6b798e9dd
