### ISSUE TITLE
sys-auth/pambase removal

### ISSUE THREAD

**Issue by c4pp4** [shiznix/unity-gentoo#202]
Old versions of sys-fs/lxcfs was removed. Starting with version 3.0.0 the cgfs PAM module has moved, and will eventually be available in app-emulation/lxc. We can add new dep app-emulation/lxc[pam] but I think it's safe to remove sys-auth/pambase. It was commited because of Unity8 applications - https://github.com/shiznix/unity-gentoo/commit/d3b93d34c7cf4d887301541701bb17b8cb05c879

**Comment by shiznix** [comment]
Yes looks like a good option - feel free to take care of and close off
