### ISSUE TITLE
Rework gnome-keyring support

### ISSUE THREAD

**Issue by c4pp4** [shiznix/unity-gentoo#203]
Using gnome-keyring along with display manager (lightdm in my case) has changed because of rework gnome-keyring support - https://bugs.gentoo.org/652194. Temporarily I have masked sys-auth/pambase-20150213-r2. With this version the keyring is not automatically unlocked when log in.

Maybe we should add new lines into /etc/pam.d/lightdm, the same lines removed from /etc/pam.d/system-login when sys-auth/pambase-20150213-r2 is installed:
auth    optional        pam_gnome_keyring.so
session optional        pam_gnome_keyring.so auto_start

**Comment by c4pp4** [comment]
x11-misc/lightdm-1.26.0_p_p0_p01-r1.ebuild
```
--- a	2018-08-13 13:37:32.291034000 +0200
+++ b	2018-11-01 17:03:08.762451530 +0100
@@ -169,6 +169,13 @@
         pamd_mimic system-local-login ${PN}-greeter auth account password session #372229
         dopamd "${FILESDIR}"/${PN}-autologin #390863, #423163
 
+	# Add gnome-keyring support to automatically
+	# unlock the keyring once you log in. Issue #203
+	sed -i \
+		-e "/auth/ a -auth\toptional\tpam_gnome_keyring.so" \
+		-e "/session/ a -session\toptional\tpam_gnome_keyring.so auto_start" \
+		"${ED}/etc/pam.d/${PN}" || die
+
 	readme.gentoo_create_doc
 	systemd_dounit "${FILESDIR}/${PN}.service"
```

/etc/pam.d/lightdm
```
# File autogenerated by pamd_mimic in pam eclass


auth    include         system-local-login
-auth   optional        pam_gnome_keyring.so
account include         system-local-login
password        include         system-local-login
session include         system-local-login
-session        optional        pam_gnome_keyring.so auto_start
```
note:
If the type value from the list above is prepended with a - character the PAM library will not log to the system log if it is not possible to load the module because it is missing in the system. This can be useful especially for modules which are not always installed on the system and are not required for correct authentication and authorization of the login session.

**Comment by shiznix** [comment]
Just tested this and works great!

No more gnome-keyring login dialog when starting the desktop session due to that Gentoo bug you mentioned earlier :)
