### ISSUE TITLE
Fix in gnome control center necessary

### ISSUE THREAD

**Issue by step21** [shiznix/unity-gentoo#204]
https://gitlab.gnome.org/GNOME/gnome-control-center/issues/49

I fixed it by changing the octal 0700 into '0700' as decribed in the issue. (in meson.build, iirc)

**Comment by shiznix** [comment]
Should be fixed in commit 4b33534a6e207baf0f2b9dff78c095f7ce122b57 thanks for reporting :)

**Comment by step21** [comment]
Thanks. For the last/next issue, I do not have a solution yet and it looks to be more complicated. One possibility is conflicting declarations between opengl/opengl.h and glew (probably imported at least in Nux) but not including opengl/gl.h which worked for a similar issue (in a different project) does not work.
