### ISSUE TITLE
Don't recognize unity profile in multiples profiles

### ISSUE THREAD

**Issue by latot** [shiznix/unity-gentoo#206]
Hi, i try install anbox, but in the midle the package dev-libs/properties-cpp request the unity profile, in my system i use multiples profiles, so i add the profile and sadly the package don't recognize i have the unity profile...

In case, to have multiples profiles, we go to /etc/portage

we remove and create again the folder make.profile

then inside we write a file with the name "parent" and inside for example:

```
gentoo:default/linux/amd64/17.0/hardened
gentoo:default/linux/amd64/17.1/systemd
unity-gentoo:linux/amd64/17.0/bionic
```

Bye.

**Comment by shiznix** [comment]
What does 'readlink /etc/portage/make.profile' say?

**Comment by latot** [comment]
Hi, is a folder, only is a link when we use one profile, with more than one is a folder with a file named "parent" with the above description.

**Comment by c4pp4** [comment]
I think anbox can be build without unity-gentoo profile - see https://github.com/shiznix/unity-gentoo/commit/09a07420936a5a334d1e65e267ea413905c23005
Feel free to re-open.
