### ISSUE TITLE
unity-menubar.patch for firefox/thunderbird fails

### ISSUE THREAD

**Issue by renegart** [shiznix/unity-gentoo#209]
thunderbird-60.5.0
Applying patches from /home/mirko/git/unity-gentoo/profiles/releases/cosmic/ehooks/mail-client/thunderbird/files ...
unity-menubar.patch ...
2 out of 5 hunks FAILED -- saving rejects to file widget/gtk/nsWidgetFactory.cpp.rej
1 out of 2 hunks FAILED -- saving rejects to file widget/gtk/nsWindow.cpp.rej
2 out of 3 hunks FAILED -- saving rejects to file widget/gtk/nsWindow.h.rej
 [ !! ]
 * ERROR: mail-client/thunderbird-60.5.0::gentoo failed (prepare phase):
 *   patch -p1  failed with /home/mirko/git/unity-gentoo/profiles/releases/cosmic/ehooks/mail-client/thunderbird/files/unity-menubar.patch

www-client/firefox-65.0
patch -p1  failed with /home/mirko/git/unity-gentoo/profiles/releases/cosmic/ehooks/www-client/firefox/files/unity-menubar.patch
  
  Call stack:
                   ebuild.sh, line  124:  Called pre_src_prepare
              profile.bashrc, line  213:  Called apply_ehook
              profile.bashrc, line 1169:  Called ebuild_hook
    02-pre_src_prepare.ehook, line    2:  Called eapply '/home/mirko/git/unity-gentoo/profiles/releases/cosmic/ehooks/www-client/firefox/files'
                 environment, line 1636:  Called _eapply_patch '/home/mirko/git/unity-gentoo/profiles/releases/cosmic/ehooks/www-client/firefox/files/unity-menubar.patch' '  '
                 environment, line 1578:  Called __helpers_die 'patch -p1  failed with /home/mirko/git/unity-gentoo/profiles/releases/cosmic/ehooks/www-client/firefox/files/unity-menubar.patch'
       isolated-functions.sh, line  121:  Called die
  The specific snippet of code:
    		die "$@"

**Comment by c4pp4** [comment]
Sorry about delay. Done.
