### ISSUE TITLE
net-libs/gnome-online-accounts removal

### ISSUE THREAD

**Issue by c4pp4** [shiznix/unity-gentoo#214]
I think we don't need to maintain it anymore as telepathy support was removed. (see changelog https://launchpad.net/ubuntu/+source/gnome-online-accounts/3.27.3-1)

We can add Ubuntu Single Sing-On support via ehooks but I think it's useless so far as it's intended for gnome-software (Software app) and software-properties (Software & Updates app) and it depends on snapd-glib. (see https://launchpad.net/bugs/1752472)

I also recommend to add USE-flag `net-libs/gnome-online-accounts -gnome` to not install gnome-base/gnome-control-center.

**Comment by shiznix** [comment]
Yup agreed, we should probably just use the main tree version.

The reasons for maintaining it are pretty much gone now.

**Comment by shiznix** [comment]
OK dropped in commit 57e050e88f8eba2cb128607e607abaed8e01b6f7 :)
