### ISSUE TITLE
ccsm doesn't find 'compizconfig'

### ISSUE THREAD

**Issue by renegart** [shiznix/unity-gentoo#216]
When try to run 'ccsm' I get following error message:
'Traceback (most recent call last):
  File "/usr/bin/ccsm", line 94, in <module>
    import compizconfig
ImportError: No module named compizconfig'

Guess it's related to 17.1 profile.

**Comment by c4pp4** [comment]
Hi, try to reinstall with the last compiz related commit.

**Comment by renegart** [comment]
Works, Thx.
