### ISSUE TITLE
anbox fatal: unable to access 'https://github.com/anbox/anbox.git/': Couldn't resolve host 'github.com'

### ISSUE THREAD

**Issue by Gooberpatrol66** [shiznix/unity-gentoo#219]
[build.log](https://github.com/shiznix/unity-gentoo/files/3700309/build.log)

**Comment by shiznix** [comment]
Can you try again? It seems there was either a problem with your network or Github were perhaps having a moment.
Closing this one as DNS name resolution to Github is out of the overlay's control.
