### ISSUE TITLE
emerge --config anbox fails with android_64.img no such file or directory

### ISSUE THREAD

**Issue by Gooberpatrol66** [shiznix/unity-gentoo#224]
[build.log](https://github.com/shiznix/unity-gentoo/files/3759594/build.log)

**Comment by shiznix** [comment]
I'm guessing you cleaned out /usr/portage/distfiles/android_amd64.img after emerging anbox and prior to running 'emerge --config ...' yes?

I'll adjust pkg_config() to use /var/lib/anbox/android_amd64.img instead.

**Comment by shiznix** [comment]
Fixed in commit a366ccc5a310723950b7227eb2685ca23b0be8d4 thanks :)

**Comment by Gooberpatrol66** [comment]
It says it's trying to look in /var/tmp/portage/app-emulation/anbox-9999.2018.07.19-r6/distdir/android_amd64.img. The /var/tmp/portage/* directories get removed if the package installs successfully, so it's gone by the time you run emerge --config.

BTW, it also needs houdini_*.sfs

**Comment by shiznix** [comment]
> It says it's trying to look in /var/tmp/portage/app-emulation/anbox-9999.2018.07.19-r6/distdir/android_amd64.img. The /var/tmp/portage/* directories get removed if the package installs successfully, so it's gone by the time you run emerge --config.
> 
> BTW, it also needs houdini_*.sfs

Sync up your local version of the overlay, *-r7 doesn't use DISTDIR anymore as per the commit mentioned above and you're still using *-r6.
Again I can see if you were to remove houdini*.sfs from your DISTFILES directly after emerging and prior to running 'emerge --config', then it would fail.

Downloading houdini*.sfs each time as part of pkg_config() would fix that problem but we'd lose hash verification on the files which SRC_URI provides currently.

**Comment by Gooberpatrol66** [comment]
>Sync up your local version of the overlay, *-r7 doesn't use DISTDIR anymore as per the commit mentioned above and you're still using -r6.
Sorry, I meant it was, not is.

>Again I can see if you were to remove houdini.sfs from your DISTFILES directly after emerging and prior to running 'emerge --config', then it would fail.
No, the files are definitely there. I can see them. The problem is, the ebuild is not looking for them in /usr/portage/distfiles, but rather in a symlink to /usr/portage/distfiles, which is located in the /var/tmp/portage directory, which does not exist after the package installs.

**Comment by Gooberpatrol66** [comment]
Are you using "ebuild unpack" etc. commands to test the ebuild instead of portage? Those probably don't clean up the /var/tmp/portage directory, which might be the source of the confusion.

**Comment by shiznix** [comment]
I see what you're saying now, it's looking for houdini*.sfs files in /var/tmp/portage/app-emulation/anbox-9999.2018.07.19-r7/distdir/
