### ISSUE TITLE
'eog-3.32.2' with ehooks fails to build

### ISSUE THREAD

**Issue by renegart** [shiznix/unity-gentoo#228]
Error: `data/meson.build:3:0: ERROR: File eog-menubar.ui does not exist.`

**Comment by c4pp4** [comment]
Thank you for reporting and sorry about that. I was testing classic diff and then I forgot to 'git add' that missing file when creating git formated patch. Fixed f75a8913e882f93cd4fbd8d6c5eb17587b689c09
