### ISSUE TITLE
unity-extra/indicator-remindor and dev-db/desktopcouch

### ISSUE THREAD

**Issue by c4pp4** [shiznix/unity-gentoo#231]
unity-extra/indicator-remindor requires:
**<dev-lang/erlang-18** - package not available
**dev-db/desktopcouch**

dev-db/desktopcouch requires:
**dev-python/gnome-keyring-python** - package not available

**Comment by eyoung100** [comment]
1. See also: https://packages.gentoo.org/packages/dev-lang/erlang
2. See also https://archives.gentoo.org/gentoo-dev/message/966440952d466fe6ce59ba1ec3e9dca6

Looks like both need an ebuild update

**Comment by c4pp4** [comment]
**dev-db/desktopcouch** requires not available packages:
dev-db/couchdb
dev-python/gnome-keyring-python
dev-python/twisted-core

**I'm going to remove the package** as it's not maintained anymore and unity-extra/indicator-remindor needs it only to migrate from couchdb to sqlitedb.
