### ISSUE TITLE
Please help with unity scopes

### ISSUE THREAD

**Issue by c4pp4** [shiznix/unity-gentoo#236]
### List of not tested scopes
If you are using some of them, please submit your experiences.

**unity-lenses/unity-lens-photos** package:
facebook\*
flickr\*
picasa\*

**unity-scopes/smart-scopes** package:
clementine
gmusicbrowser
gnote
guayadeque
musique
sshsearch
zotero _(note: Zotero 4.0 for Firefox is being replaced by a Zotero Connector for Firefox)_

\* _remote scopes, need 'Include online search results' option to be turned on, the option is located in System Settings > Security & Privacy > Search tab_

**Comment by c4pp4** [comment]
## List of not working scopes
gdrive - account-plugins package not available
googlenews
gourmet - gourmet package not available
launchpad - python-launchpadlib package not available
openclipart - https://en.wikipedia.org/wiki/Openclipart#Lockdown_and_attempts_at_mirroring_the_library

openweathermap - needs API key
tomboy - tomboy package not available
yahoostock

**Comment by shiznix** [comment]
Personally I hardly ever use them at all, but that's not to say they shouldn't be there....
Unfortunately no longer had they just been implemented then their development all got paused to concentrate on the now defunct Unity8 :/

**Comment by c4pp4** [comment]
@shiznix 
How about to not install smart-scopes and facebook/flickr/picasa scopes by deafult?

**Comment by c4pp4** [comment]
I'm closing this off now, feel free to reopen.

**Comment by shiznix** [comment]
Hi @c4pp4 I'd suggest defaults just roll with whatever we get when installing Unity on current Ubuntu, to keep the desktop experience as closely matched to what upstream are maintaining and presenting.

Apologies for my lag in reply, have been spreading myself very thin on various projects due to this whole COVID lockdown thing, homeschooling the kids has taken some priority.

Thanks :)

**Comment by c4pp4** [comment]
@shiznix 
No problem :)

Current (eoan) Ubuntu is providing unity-lens-{applications,files} and unity-scope-home by default. We are providing the same plus unity-lens-{music,photos,video}. Additionally you can add smart-scopes and facebook/flick/picasa via USE-flags.
