### ISSUE TITLE
Some programs can't be started by launcher

### ISSUE THREAD

**Issue by renegart** [shiznix/unity-gentoo#242]
On one system I've the issue I can't start some of the programs pinned on it.
For instance 'x11-terms/terminator'. On other systems it works.
Starting it via 'Alt-F2' works. It's also not possible to find it on Dash.

A complete recompile of the system doesn't help.

How can I figure out what's going wrong?

**Comment by c4pp4** [comment]
You can try to launch it via new user account on the same system to exclude user specific settings.

**Comment by shiznix** [comment]
+1 on trying with a fresh user on the affected system to troubleshoot.

Dash populates itself by looking at /usr/share/applications/*.desktop files but does so using glib if that helps narrow things down.

**Comment by renegart** [comment]
After deleting *.deskop files under ~/.local/share/applications it works again
