### ISSUE TITLE
Error messages: die "No supported implementation in PYTHON_COMPAT."

### ISSUE THREAD

**Issue by renegart** [shiznix/unity-gentoo#246]
Since today I get following Error Message:  die "No supported implementation in PYTHON_COMPAT."

Gentoo has changed the Python implementation

**Comment by c4pp4** [comment]
**Updated**:
dev-cpp/gtest b88e50148c22a9974c6a62d2602c2f48a6da3bad
unity-base/evemu b88e50148c22a9974c6a62d2602c2f48a6da3bad
unity-base/unity-gtk-module abffaa9ae0613b43ffccfaf63f4c48060b645400

**Remain**:
app-emulation/anbox/anbox-9999.2018.07.19-r10.ebuild
dev-python/configglue/configglue-1.0.ebuild
dev-python/python-testscenarios/python-testscenarios-0.5.0_p_p3_p01.ebuild
gnome-base/gnome-menus/gnome-menus-3.0.1-r3.ebuild
unity-extra/indicator-classicmenu/indicator-classicmenu-0.11_p_p0_p01.ebuild
unity-extra/indicator-netspeed/indicator-netspeed-9999.ebuild
unity-extra/indicator-privacy/indicator-privacy-0.05.ebuild
unity-extra/indicator-remindor/indicator-remindor-13.02.ebuild
unity-indicators/indicator-internode/indicator-internode-9999.ebuild

**Comment by shiznix** [comment]
Have updated all remaining core Unity packages in commit adb57ce9f4205e584d0c330dd03a91da89362e04

Only ebuilds in categories unity-extra/ and unity-indicators/ remain to be updated.

**Comment by maxmadzz** [comment]
```
Calculating dependencies \ * ERROR: app-emulation/anbox-9999.2018.07.19-r10::unity-gentoo failed (depend phase):
 *   No supported implementation in PYTHON_COMPAT.
 * 
 * Call stack:
 *                          ebuild.sh, line 609:  Called source '/var/lib/layman/unity-gentoo/app-emulation/anbox/anbox-9999.2018.07.19-r10.ebuild'
 | *   anbox-9999.2018.07.19-r10.ebuild, line   7:  Called inherit 'cmake-utils' 'git-r3' 'linux-info' 'python-single-r1' 'systemd' 'udev' 'versionator'
 *                          ebuild.sh, line 314:  Called __qa_source '/var/db/repos/gentoo/eclass/python-single-r1.eclass'
 *                          ebuild.sh, line 112:  Called source '/var/db/repos/gentoo/eclass/python-single-r1.eclass'
 / *            python-single-r1.eclass, line 269:  Called _python_single_set_globals
 *            python-single-r1.eclass, line 209:  Called _python_set_impls
 *             python-utils-r1.eclass, line 156:  Called die
 * The specific snippet of code:
 | *   			die "No supported implementation in PYTHON_COMPAT."
 * 
 * If you need support, post the output of `emerge --info '=app-emulation/anbox-9999.2018.07.19-r10::unity-gentoo'`,
 * the complete build log and the output of `emerge -pqv '=app-emulation/anbox-9999.2018.07.19-r10::unity-gentoo'`.
 * Working directory: '/usr/lib/python3.8/site-packages'
 * S: '/var/tmp/portage/app-emulation/anbox-9999.2018.07.19-r10/work/anbox-9999.2018.07.19'
... done!

!!! All ebuilds that could satisfy "anbox" have been masked.
!!! One of the following masked packages is required to complete your request:
- app-emulation/anbox-9999.2018.07.19-r10::unity-gentoo (masked by: corruption)

For more information, see the MASKED PACKAGES section in the emerge
man page or refer to the Gentoo Handbook.

```

**Comment by shiznix** [comment]
All overlay packages have now been moved or deprecated to support Python3.

Closing this issue now, thanks for reporting :)
