### ISSUE TITLE
'gnome-extra/zeitgeist-1.0.3_p_p4_p01' fails to compile

### ISSUE THREAD

**Issue by renegart** [shiznix/unity-gentoo#252]
`
zeitgeist-1.0.3

  Build environment
    Install Prefix:        /usr

  Optional dependencies
    fts++:                 yes
    dee-icu:               yes

  Other build options:
    DataHub:               yes
      Telepathy provider:  no
      Downloads monitor:   yes
    SQL debugging:         no
    libzeitgeist docs:     no
    GObject Introspection: yes

make  all-recursive
make[1]: Entering directory '/var/tmp/portage/gnome-extra/zeitgeist-1.0.3_p_p4_p01/work/zeitgeist-1.0.3'
Making all in libzeitgeist
make[2]: Entering directory '/var/tmp/portage/gnome-extra/zeitgeist-1.0.3_p_p4_p01/work/zeitgeist-1.0.3/libzeitgeist'
/usr/bin/valac-0.52 \
	--target-glib=2.36 --pkg gio-2.0 --pkg gio-unix-2.0 --pkg sqlite3 ../config.vapi -C   --vapi zeitgeist-datamodel-2.0.vapi -H zeitgeist-datamodel.h --library zeitgeist-2.0  \
	data-source.vala errors.vala mimetype.vala enumerations.vala event.vala subject.vala timerange.vala timestamp.vala ontology-uris.vala ontology.vala result-set.vala simple-result-set.vala utils.vala
event.vala:250.24-250.56: warning: Access to possible `null'. Perform a check or use an unsafe cast.
                path = (info as DesktopAppInfo).filename;
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
timestamp.vala:77.32-77.46: warning: `GLib.TimeVal' has been deprecated since 2.62
timestamp.vala:95.27-95.33: warning: `GLib.TimeVal' has been deprecated since 2.62
timestamp.vala:95.17-95.23: warning: `GLib.TimeVal' has been deprecated since 2.62
timestamp.vala:122.27-122.33: warning: `GLib.TimeVal' has been deprecated since 2.62
timestamp.vala:122.17-122.23: warning: `GLib.TimeVal' has been deprecated since 2.62
timestamp.vala:139.17-139.23: warning: `GLib.TimeVal' has been deprecated since 2.62
timestamp.vala:185.17-185.23: warning: `GLib.TimeVal' has been deprecated since 2.62
timestamp.vala:186.9-186.25: warning: `GLib.Date.set_time_val' has been deprecated since 2.62
errors.vala:39.5-39.43: warning: Method `Zeitgeist.vala_bug_workaround' never used
    private static void vala_bug_workaround ()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
event.vala:299.5-299.47: warning: Method `Zeitgeist.Event.optimize_variant_allocation' never used
    private Variant optimize_variant_allocation (Variant event_variant) {
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Compilation succeeded - 11 warning(s)
touch libzeitgeist_datamodel_2_0_la_vala.stamp
/usr/bin/valac-0.52 \
	--target-glib=2.36 --pkg gio-2.0 --pkg gio-unix-2.0 --pkg sqlite3 ../config.vapi -C   ./zeitgeist-datamodel-2.0.vapi --vapi zeitgeist-internal.vapi -H zeitgeist-internal.h  \
	db-reader.vala sql.vala sql-schema.vala table-lookup.vala where-clause.vala
sql.vala:456.13-457.55: warning: unhandled error `Zeitgeist.EngineError'
where-clause.vala:219.35-219.63: error: The name `pdata' does not exist in the context of `GLib.PtrArray*'
            Memory.copy(pointers, ((PtrArray *) gptrarr)->pdata,
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Compilation failed: 1 error(s), 1 warning(s)
make[2]: *** [Makefile:1298: libzeitgeist_internal_la_vala.stamp] Error 1
make[2]: Leaving directory '/var/tmp/portage/gnome-extra/zeitgeist-1.0.3_p_p4_p01/work/zeitgeist-1.0.3/libzeitgeist'
make[1]: *** [Makefile:551: all-recursive] Error 1
make[1]: Leaving directory '/var/tmp/portage/gnome-extra/zeitgeist-1.0.3_p_p4_p01/work/zeitgeist-1.0.3'
make: *** [Makefile:462: all] Error 2
`

**Comment by c4pp4** [comment]
@renegart
Hi, I forked the overlay and I mainly work on the fork. You can find some fixes here: https://github.com/c4pp4/gentoo-unity7 and push them into this overlay. Thank you.

**Comment by renegart** [comment]
@c4pp4 are you planning to merge your changes back to this repo?

**Comment by c4pp4** [comment]
@renegart I was planning to do it but I changed my mind because there are too many changes and @shiznix denied some of them and it seems he is not active anymore. Fork is stable and up-to-date if you are interested or you can merge anything from it, it's up to you.

**Comment by shiznix** [comment]
Apologies for missing this one, looks like it automagically succeeds with vala:0.44 installed as added in -r1 DEPENDs?

Closing as fixed in commit 37ac059f3cca0a4b3f9f1c06f11480429871ded6
