### ISSUE TITLE
unity-base/compiz-0.9.14.1_p20200813_p0_p04 Fails to compile

### ISSUE THREAD

**Issue by RetronEletron** [shiznix/unity-gentoo#253]
Basically i really wanted to have Unity on Gentoo so while installing i added the overlay then installed the package thing and then ran the updating the world section bit but at this specific package it just fails at 16% always i tried everything and i got no idea
anyway for some info

https://pastebin.com/EUsszBGY Logs

https://pastebin.com/sargdKJX Make.conf

Anymore more detail then please contact me and please help me resolve the issue.

EDIT:
Btw I am having the [38]  unity-gentoo:linux/amd64/17.1/hirsute (stable) * profile

**Comment by c4pp4** [comment]
Can you try:
MAKEOPTS="-j1" emerge -av1 compiz
