### ISSUE TITLE
All ebuilds that could satisfy "unity-lenses/unity-lens-applications" have been masked. Issue

### ISSUE THREAD

**Issue by RetronEletron** [shiznix/unity-gentoo#254]
Hello i report again but this time of an odd issue not the normal stuff like masked by ~amd64 or whatever just this:

!!! All ebuilds that could satisfy "unity-lenses/unity-lens-applications" have been masked.
!!! One of the following masked packages is required to complete your request:
- unity-lenses/unity-lens-applications-7.1.0_p20160927_p0_p05-r2::unity-gentoo (masked by: invalid: DEPEND: expected: dependency string, got: ')', token 11)

Now this seems like an broken ebuild to be honest so if you find any solution but tell me.

**Comment by c4pp4** [comment]
@RetronEletron Hi, the project is currently unmaintained, you can try a fork: https://github.com/c4pp4/gentoo-unity7

**Comment by RetronEletron** [comment]
Ok i will try that

**Comment by RetronEletron** [comment]
That seems more maintained

**Comment by RetronEletron** [comment]
Yay thx it works just fine now close this issue.
