### ISSUE TITLE
Arm64 Support

### ISSUE THREAD

**Issue by anoraktrend** [shiznix/unity-gentoo#256]
I use an RPi400 for a desktop PC and I would love to use Gentoo Unity on it, unfortunately the keywords make that impossible. It shouldn't be impossible to compile it on arm64, but because of missing keywords, it is.

**Comment by shiznix** [comment]
Hi @anoraktrend,

Thanks for your interest but unfortunately I don't have an RPi400 or arm64 device to enable testing or maintaining that keyword.

I don't feel it would be right to subject someone to that, but you're more than welcome to fork the repo and enable it yourself, it might just work out-the-box.

Good luck :)

**Comment by tidux** [comment]
@shiznix post a Monero donation address in the readme and funding for an RPi can be handled.

**Comment by anoraktrend** [comment]
(The above response is a good one)
