### ISSUE TITLE
Trusty it's not possible too show/hide mounted drive icons on desktop

### ISSUE THREAD

**Issue by renegart** [shiznix/unity-gentoo#88]
It's not possible too show/hide the drive icons on the desktop via UnityTweekTool

Workaround:
'gsettings set org.gnome.nautilus.desktop volumes-visible true' -> shows icons
'gsettings set org.gnome.nautilus.desktop volumes-visible false' -> hides icons

-> UnityTweekTool may needs to be updated.

**Comment by shiznix** [comment]
Fixed in commit 9a8665b7d4d9bc3f50c6e38e257c2139be5dfe15
