### ISSUE TITLE
Power options in unity control panel are greyed out when it comes to hibernate/sleep

### ISSUE THREAD

**Issue by VABAV** [shiznix/unity-gentoo#98]
My power options in unity control panel are greyed out when it comes to hibernate/sleep. It's fresh install with systemd. I also tried installing acpid. With upower-pm-tools the options are enabled but for example with lid close action it is not effective (maybe it is that [bug](https://www.libreoffice.org/bugzilla/show_bug.cgi?id=76267)).

**Comment by shiznix** [comment]
unity-control-center and unity-settings-daemon have now matured to a point where this now works with recent upower and systemd changes.
